configuration: Release

# Restore NuGet Packages
before_build:
 - nuget Restore c:\project\aenima\scr\Aenima.sln

# Configure build
build:
  parallel: true                 
  project: c:\project\aenima\scr\Aenima.sln