version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{appveyor_repo_branch}"

os: Visual Studio 2015 RC # To allow C#6 syntax

clone_folder: c:\projects\Aenima

configuration: Release

install:
 - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

platform:
 - Any CPU

before_build:
 - nuget Restore src\Aenima.sln -PackagesDirectory \packages

build:
  parallel: true                 
  project: src\Aenima.sln
  publish_nuget: false
  #verbosity: minimal


