clone_folder: c:\project\

configuration: Release

platform:
 - Any CPU

before_build:
 - nuget Restore src\Aenima.sln -PackagesDirectory c:\project\Aenima\packages

build:
  parallel: true                 
  project: src\Aenima.sln
  publish_nuget: false
  verbosity: minimal


