platform:
 - Any CPU

configuration: Release

build:
  parallel: true                 
  project: Aenima.sln
  publish_nuget: false
  verbosity: minimal

# Restore NuGet Packages
before_build:
 - cd c:\project\src
 - nuget Restore Aenima.sln -PackagesDirectory c:\project\Aenima\packages

