clone_folder: c:\projects\Aenima

configuration: Release

platform:
 - Any CPU

before_build:
 - nuget Restore src\Aenima.sln -PackagesDirectory \packages

build:
  parallel: true                 
  project: src\Aenima.sln
  publish_nuget: false
  verbosity: minimal


